name: Generate Datas
on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Contribution Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: Ns-AnoNymouS
          outputs: dist/github-contribution-grid-snake.svg

      # Deploy the generated SVG to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
